version: '3.4'

services:
  postgres-db:
    image: postgres
    container_name: PostgreSQL
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=repository_sample
    volumes: 
        - pg-data:/var/lib/postgresql/data
    restart: always
    ports:
        - "5432:5432"
    networks:
        repository_sample_network:

volumes:
  pg-data:
    name: repository-sample-database

networks:
    repository_sample_network:
