name: .NET Core
on:
  push:
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        #source-url: https://nuget.pkg.github.com/giuneco/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Setup nuget config
      run:  sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' src/nuget.src > nuget.config
      working-directory: src/EFCore.LazyRepository
    - name: Install dependencies
      run:  dotnet restore EFCore.LazyRepository.csproj
      working-directory: src/EFCore.LazyRepository
    - name: Build
      run: dotnet build EFCore.LazyRepository.csproj --configuration Release --no-restore
      working-directory: src/EFCore.LazyRepository
    - name: Generate a NuGet package
      run: dotnet pack --configuration Release -o nupkg --version-suffix ${{ github.run_number }} -p:PackageVersion="1.5.${{ github.run_number }}"
      working-directory: src/EFCore.LazyRepository
    - name: Push to GitHub package registry
      run: dotnet nuget push "nupkg/*.nupkg"  --skip-duplicate -s "https://nuget.pkg.github.com/mattiabonanni/index.json" -k ${{ secrets.GITHUB_TOKEN }}
      working-directory: src/EFCore.LazyRepository
