name: Build

on:
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/EFCore.LazyRepository
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/EFCore.LazyRepository
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/EFCore.LazyRepository

  pack:
    
    runs-on: ubuntu-latest
    
    needs: build
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Determine version
      run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION ./src/EFCore.LazyRepository
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
        
  publish:
    
    runs-on: ubuntu-latest
    
    needs: pack
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: Push Nupkg to GitHub Packages
      # You may pin to the exact commit or the version.
      # uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@462b6006e5c90f732d030b0ace2c3e7ee9d550bc
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        # Path of NuPkg
        nupkg-path: ./artifacts/*.nupkg
        # package repository owner
        repo-owner: MattiaBonanni
        # user account
        gh-user: MattiaBonanni
        # access token
        token: ${{ secrets.GITHUB_TOKEN }}
